<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="shinytest2-tm_g_scatterplot" timestamp="2024-04-15T09:29:12Z" hostname="9f1a85ba1939" tests="6" skipped="0" failures="0" errors="6" time="614.234">
    <testcase time="104.268" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_module_is_initialised_with_the_specified_defaults">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:89:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:29:15.36 Start AppDriver initialization
{shinytest2} R  info   09:29:15.43 Starting Shiny app
{shinytest2} R  info   09:29:16.67 Creating new ChromoteSession
{shinytest2} R  info   09:29:16.74 Navigating to Shiny app
{shinytest2} R  info   09:29:16.83 Injecting shiny-tracer.js
{chromote}   JS info   09:29:16.86 shinytest2; jQuery not found
{chromote}   JS info   09:29:16.87 shinytest2; Loaded
{shinytest2} R  info   09:29:16.87 Waiting for Shiny to become ready
{chromote}   JS info   09:29:16.94 shinytest2; jQuery found
{chromote}   JS info   09:29:16.94 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:29:16.99 shinytest2; Connected
{chromote}   JS info   09:29:17.03 shinytest2; shiny:busy
{shinytest2} R  info   09:29:17.08 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:29:17.08 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:29:18.33 shinytest2; shiny:idle
{chromote}   JS info   09:29:18.33 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:29:18.33 shinytest2; shiny:value error
{chromote}   JS info   09:29:18.33 shinytest2; shiny:busy
{chromote}   JS info   09:29:18.33 shinytest2; shiny:idle
{chromote}   JS info   09:29:18.36 shinytest2; shiny:busy
{shinytest2} R  info   09:30:57.11 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:7233
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:89:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
    <testcase time="101.906" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_base_for_the_log_transformation_can_be_applied">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:118:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:30:57.58 Start AppDriver initialization
{shinytest2} R  info   09:30:57.62 Starting Shiny app
{shinytest2} R  info   09:30:58.65 Creating new ChromoteSession
{shinytest2} R  info   09:30:58.69 Navigating to Shiny app
{shinytest2} R  info   09:30:58.77 Injecting shiny-tracer.js
{chromote}   JS info   09:30:58.78 shinytest2; jQuery not found
{chromote}   JS info   09:30:58.78 shinytest2; Loaded
{shinytest2} R  info   09:30:58.78 Waiting for Shiny to become ready
{chromote}   JS info   09:30:58.87 shinytest2; jQuery found
{chromote}   JS info   09:30:58.87 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:30:58.92 shinytest2; Connected
{chromote}   JS info   09:30:58.97 shinytest2; shiny:busy
{shinytest2} R  info   09:30:59.00 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:30:59.01 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:31:00.22 shinytest2; shiny:idle
{chromote}   JS info   09:31:00.22 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:31:00.22 shinytest2; shiny:value error
{chromote}   JS info   09:31:00.22 shinytest2; shiny:busy
{chromote}   JS info   09:31:00.22 shinytest2; shiny:idle
{chromote}   JS info   09:31:00.25 shinytest2; shiny:busy
{shinytest2} R  info   09:32:39.02 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:7862
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:118:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
    <testcase time="101.87" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_base_for_the_log_transformation_can_be_applied">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:132:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:32:39.47 Start AppDriver initialization
{shinytest2} R  info   09:32:39.51 Starting Shiny app
{shinytest2} R  info   09:32:40.54 Creating new ChromoteSession
{shinytest2} R  info   09:32:40.57 Navigating to Shiny app
{shinytest2} R  info   09:32:40.65 Injecting shiny-tracer.js
{chromote}   JS info   09:32:40.66 shinytest2; jQuery not found
{chromote}   JS info   09:32:40.66 shinytest2; Loaded
{shinytest2} R  info   09:32:40.66 Waiting for Shiny to become ready
{chromote}   JS info   09:32:40.75 shinytest2; jQuery found
{chromote}   JS info   09:32:40.75 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:32:40.81 shinytest2; Connected
{chromote}   JS info   09:32:40.85 shinytest2; shiny:busy
{shinytest2} R  info   09:32:40.88 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:32:40.88 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:32:42.06 shinytest2; shiny:idle
{chromote}   JS info   09:32:42.06 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:32:42.06 shinytest2; shiny:value error
{chromote}   JS info   09:32:42.06 shinytest2; shiny:busy
{chromote}   JS info   09:32:42.07 shinytest2; shiny:idle
{chromote}   JS info   09:32:42.09 shinytest2; shiny:busy
{shinytest2} R  info   09:34:20.90 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:7172
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:132:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
    <testcase time="102.08" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_log_transform_is_only_possible_for_positive_numeric_vars">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:146:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:34:21.33 Start AppDriver initialization
{shinytest2} R  info   09:34:21.37 Starting Shiny app
{shinytest2} R  info   09:34:22.61 Creating new ChromoteSession
{shinytest2} R  info   09:34:22.64 Navigating to Shiny app
{shinytest2} R  info   09:34:22.74 Injecting shiny-tracer.js
{chromote}   JS info   09:34:22.74 shinytest2; jQuery not found
{chromote}   JS info   09:34:22.74 shinytest2; Loaded
{shinytest2} R  info   09:34:22.75 Waiting for Shiny to become ready
{chromote}   JS info   09:34:22.84 shinytest2; jQuery found
{chromote}   JS info   09:34:22.84 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:34:22.89 shinytest2; Connected
{chromote}   JS info   09:34:22.93 shinytest2; shiny:busy
{shinytest2} R  info   09:34:22.97 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:34:22.97 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:34:24.22 shinytest2; shiny:idle
{chromote}   JS info   09:34:24.22 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:34:24.22 shinytest2; shiny:value error
{chromote}   JS info   09:34:24.23 shinytest2; shiny:busy
{chromote}   JS info   09:34:24.23 shinytest2; shiny:idle
{chromote}   JS info   09:34:24.25 shinytest2; shiny:busy
{shinytest2} R  info   09:36:02.98 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:6359
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:146:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
    <testcase time="102.048" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_get_validation_error_when_facetting_with_the_same_row_col_variable">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:165:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:36:03.40 Start AppDriver initialization
{shinytest2} R  info   09:36:03.44 Starting Shiny app
{shinytest2} R  info   09:36:04.67 Creating new ChromoteSession
{shinytest2} R  info   09:36:04.70 Navigating to Shiny app
{shinytest2} R  info   09:36:04.79 Injecting shiny-tracer.js
{chromote}   JS info   09:36:04.79 shinytest2; jQuery not found
{chromote}   JS info   09:36:04.80 shinytest2; Loaded
{shinytest2} R  info   09:36:04.80 Waiting for Shiny to become ready
{chromote}   JS info   09:36:04.89 shinytest2; jQuery found
{chromote}   JS info   09:36:04.89 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:36:04.95 shinytest2; Connected
{chromote}   JS info   09:36:05.00 shinytest2; shiny:busy
{shinytest2} R  info   09:36:05.02 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:36:05.02 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:36:06.23 shinytest2; shiny:idle
{chromote}   JS info   09:36:06.23 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:36:06.23 shinytest2; shiny:value error
{chromote}   JS info   09:36:06.23 shinytest2; shiny:busy
{chromote}   JS info   09:36:06.23 shinytest2; shiny:idle
{chromote}   JS info   09:36:06.26 shinytest2; shiny:busy
{shinytest2} R  info   09:37:45.03 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:4116
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:165:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
    <testcase time="102.062" classname="shinytest2_tm_g_scatterplot" name="e2e_tm_g_scatterplot_encoding_inputs_produce_output_without_validation_errors">
      <error type="error" message="Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout,  ('test-shinytest2-tm_g_scatterplot.R:177:3')">Error in `app_initialize(self, private, app_dir = app_dir, ..., load_timeout = load_timeout, 
    timeout = timeout, wait = wait, expect_values_screenshot_args = expect_values_screenshot_args, 
    screenshot_args = screenshot_args, check_names = check_names, 
    name = name, variant = variant, view = view, height = height, 
    width = width, seed = seed, clean_logs = clean_logs, shiny_args = shiny_args, 
    render_args = render_args, options = options)`: Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable


ℹ You can inspect the failed AppDriver object via `rlang::last_error()$app`
ℹ AppDriver logs:
{shinytest2} R  info   09:37:45.46 Start AppDriver initialization
{shinytest2} R  info   09:37:45.50 Starting Shiny app
{shinytest2} R  info   09:37:46.74 Creating new ChromoteSession
{shinytest2} R  info   09:37:46.77 Navigating to Shiny app
{shinytest2} R  info   09:37:46.86 Injecting shiny-tracer.js
{chromote}   JS info   09:37:46.87 shinytest2; jQuery not found
{chromote}   JS info   09:37:46.87 shinytest2; Loaded
{shinytest2} R  info   09:37:46.87 Waiting for Shiny to become ready
{chromote}   JS info   09:37:46.98 shinytest2; jQuery found
{chromote}   JS info   09:37:46.98 shinytest2; Waiting for shiny session to connect
{chromote}   JS info   09:37:47.04 shinytest2; Connected
{shinytest2} R  info   09:37:47.08 Waiting for Shiny to become idle for 200ms within 1e+05ms
{chromote}   JS info   09:37:47.09 shinytest2; Waiting for Shiny to be stable
{chromote}   JS info   09:37:47.10 shinytest2; shiny:busy
{chromote}   JS info   09:37:48.37 shinytest2; shiny:idle
{chromote}   JS info   09:37:48.37 shinytest2; shiny:value teal-identifier
{chromote}   JS info   09:37:48.37 shinytest2; shiny:value error
{chromote}   JS info   09:37:48.38 shinytest2; shiny:busy
{chromote}   JS info   09:37:48.38 shinytest2; shiny:idle
{chromote}   JS info   09:37:48.41 shinytest2; shiny:busy
{shinytest2} R  info   09:39:27.10 Error while initializing AppDriver:
                                   Shiny app did not become stable in 1e+05ms.
                                   Message: An error occurred while waiting for Shiny to be stable
                                   Caused by error in `app_wait_for_idle()`:
                                   ! An error occurred while waiting for Shiny to be stable
{shiny}      R  stderr ----------- Loading required package: shiny
{shiny}      R  stderr ----------- Attempting to load the environment ‘package:nestcolor’
{shiny}      R  stderr ----------- Loading required package: teal.data
{shiny}      R  stderr ----------- Loading required package: teal.code
{shiny}      R  stderr ----------- Loading required package: teal.slice
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- You are using teal version 0.15.2.9026
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Attaching package: ‘teal’
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- The following objects are masked from ‘package:teal.slice’:
{shiny}      R  stderr ----------- 
{shiny}      R  stderr -----------     as.teal_slices, teal_slices
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Running application in test mode.
{shiny}      R  stderr ----------- 
{shiny}      R  stderr ----------- Listening on http://127.0.0.1:3306
{shiny}      R  stderr ----------- Initializing reporter_previewer_module
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   153: facet_ggplot_call
{shiny}      R  stderr -----------   152: &lt;reactive&gt;
{shiny}      R  stderr -----------   136: output_q
{shiny}      R  stderr -----------   135: &lt;reactive&gt;
{shiny}      R  stderr -----------   119: plot_r
{shiny}      R  stderr -----------   110: renderUI
{shiny}      R  stderr -----------   109: func
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-scatter_plot-plot_out_main
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   134: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   133: stop
{shiny}      R  stderr -----------   132: output_q
{shiny}      R  stderr -----------   117: exprFunc
{shiny}      R  stderr -----------   116: widgetFunc
{shiny}      R  stderr -----------   115: ::
{shiny}      R  stderr ----------- htmlwidgets
{shiny}      R  stderr ----------- shinyRenderWidget
{shiny}      R  stderr -----------   114: func
{shiny}      R  stderr -----------   101: renderFunc
{shiny}      R  stderr -----------   100: renderFunc
{shiny}      R  stderr -----------    96: renderFunc
{shiny}      R  stderr -----------    95: output$teal-main_ui-root-scatterplot_choices-module-data_table
{shiny}      R  stderr -----------    14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------    10: base::do.call
{shiny}      R  stderr -----------     9: base::saveRDS
{shiny}      R  stderr -----------     8: base::withCallingHandlers
{shiny}      R  stderr -----------     7: doTryCatch
{shiny}      R  stderr -----------     6: tryCatchOne
{shiny}      R  stderr -----------     5: tryCatchList
{shiny}      R  stderr -----------     2: tryCatchList
{shiny}      R  stderr -----------     1: base::tryCatch
{shiny}      R  stderr ----------- Warning: Error in facet_ggplot_call: non-interactive browser() -- left over from debugging?
{shiny}      R  stderr -----------   14: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   12: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   11: &lt;Anonymous&gt;
{shiny}      R  stderr -----------   10: base::do.call
{shiny}      R  stderr -----------    9: base::saveRDS
{shiny}      R  stderr -----------    8: base::withCallingHandlers
{shiny}      R  stderr -----------    7: doTryCatch
{shiny}      R  stderr -----------    6: tryCatchOne
{shiny}      R  stderr -----------    5: tryCatchList
{shiny}      R  stderr -----------    2: tryCatchList
{shiny}      R  stderr -----------    1: base::tryCatch


Caused by error in `app_initialize_()`:
! Shiny app did not become stable in 1e+05ms.
Message: An error occurred while waiting for Shiny to be stable
Caused by error in `app_wait_for_idle()`:
! An error occurred while waiting for Shiny to be stable
Backtrace:
     ▆
  1. ├─teal.modules.general (local) app_driver_tm_g_scatterplot() at test-shinytest2-tm_g_scatterplot.R:177:3
  2. │ └─TealAppDriver$new(...) at test-shinytest2-tm_g_scatterplot.R:10:3
  3. │   └─teal (local) initialize(...)
  4. │     ├─base::suppressWarnings(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     └─super$initialize(...)
  7. │       └─shinytest2:::app_initialize(...)
  8. │         ├─base::withCallingHandlers(...)
  9. │         └─shinytest2:::app_initialize_(self, private, ..., view = view)
 10. │           ├─base::withCallingHandlers(...)
 11. │           └─self$wait_for_idle(duration = 200, timeout = private$load_timeout)
 12. │             └─shinytest2:::app_wait_for_idle(...)
 13. │               └─shinytest2:::app_abort(self, private, "An error occurred while waiting for Shiny to be stable")
 14. │                 └─rlang::abort(..., app = self, call = call)
 15. │                   └─rlang:::signal_abort(cnd, .file)
 16. │                     └─base::signalCondition(cnd)
 17. ├─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 18. │ └─shinytest2:::app_abort(...)
 19. │   └─rlang::abort(..., app = self, call = call)
 20. │     └─rlang:::signal_abort(cnd, .file)
 21. │       └─base::signalCondition(cnd)
 22. └─shinytest2 (local) `&lt;fn&gt;`(`&lt;rlng_rrr&gt;`)
 23.   └─shinytest2:::app_abort(...)
 24.     └─rlang::abort(..., app = self, call = call)</error>
    </testcase>
  </testsuite>
  <testsuite name="tm_g_bivariate" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="18" skipped="0" failures="0" errors="0" time="0.181">
    <testcase time="0.0629999999999882" classname="tm_g_bivariate" name="tm_g_bivariate_creates_a_teal_module_object"/>
    <testcase time="0.00499999999999545" classname="tm_g_bivariate" name="tm_g_bivariate_creates_a_teal_module_object_with_default_options"/>
    <testcase time="0.00999999999999091" classname="tm_g_bivariate" name="tm_g_bivariate_creates_a_teal_module_object_with_multiple_data_extract_specs"/>
    <testcase time="0.00499999999999545" classname="tm_g_bivariate" name="tm_g_bivariate_creates_a_module_with_datanames_taken_from_data_extracts"/>
    <testcase time="0.0080000000000382" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_x_contains_a_spec_with_multiple_selection"/>
    <testcase time="0.00699999999994816" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_x_contains_multiple_spec_with_at_least_one_multiple_selection"/>
    <testcase time="0.00700000000006185" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_x_contains_multiple_spec_with_at_least_one_multiple_selection"/>
    <testcase time="0.00699999999994816" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_y_contains_multiple_spec_with_at_least_one_multiple_selection"/>
    <testcase time="0.0080000000000382" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_height_is_not_valid"/>
    <testcase time="0.00599999999997181" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_height_is_not_valid"/>
    <testcase time="0.00700000000006185" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_height_is_not_valid"/>
    <testcase time="0.00699999999994816" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_width_is_not_valid"/>
    <testcase time="0.00700000000006185" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_width_is_not_valid"/>
    <testcase time="0.00699999999994816" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_plot_width_is_not_valid"/>
    <testcase time="0.00699999999994816" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_color_setting_is_FALSE_and_color_is_supplied"/>
    <testcase time="0.0080000000000382" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_color_setting_is_FALSE_and_size_is_supplied"/>
    <testcase time="0.00700000000006185" classname="tm_g_bivariate" name="tm_g_bivariate_fails_when_color_setting_is_FALSE_and_fill_is_supplied"/>
    <testcase time="0.00499999999999545" classname="tm_g_bivariate" name="tm_g_bivariate_determines_color_size_and_fill_when_color_setting_is_TRUE"/>
  </testsuite>
  <testsuite name="bivariate_ggplot_call" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="21" skipped="0" failures="0" errors="0" time="0.078">
    <testcase time="0.0169999999999391" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_numerics"/>
    <testcase time="0.00200000000006639" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_numerics"/>
    <testcase time="0.00299999999992906" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_numerics"/>
    <testcase time="0.00200000000006639" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_numerics"/>
    <testcase time="0.00499999999999545" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00300000000004275" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00300000000004275" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00200000000006639" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_factor_char_logical"/>
    <testcase time="0.00499999999999545" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00299999999992906" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00200000000006639" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00300000000004275" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_numeric"/>
    <testcase time="0.00999999999999091" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_factor"/>
    <testcase time="0.00300000000004275" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_factor"/>
    <testcase time="0.00199999999995271" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_factor"/>
    <testcase time="0.00300000000004275" classname="bivariate_ggplot_call" name="bivariate_ggplot_call_with_single_data_factor"/>
  </testsuite>
  <testsuite name="front_page" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="4" skipped="0" failures="0" errors="0" time="0.019">
    <testcase time="0.00599999999997181" classname="front_page" name="convert_metadata_to_dataframe_returns_a_data_frame_with_no_rows_if_no_metadata"/>
    <testcase time="0.00499999999999545" classname="front_page" name="convert_metadata_to_dataframe_returns_a_data_frame_with_metadata_if_more_than_one_dataset"/>
    <testcase time="0.0040000000000191" classname="front_page" name="convert_metadata_to_dataframe_returns_a_data_frame_with_metadata_if_one_dataset"/>
    <testcase time="0.0040000000000191" classname="front_page" name="convert_metadata_to_dataframe_converts_metadata_values_to_characters"/>
  </testsuite>
  <testsuite name="g_expert_cl" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="15" skipped="0" failures="0" errors="0" time="0.027">
    <testcase time="0.00599999999997181" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.00200000000006639" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations"/>
    <testcase time="0.0040000000000191" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations_without_colour_var"/>
    <testcase time="0.00100000000009004" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations_without_colour_var"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations_without_colour_var"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations_without_colour_var"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_with_all_combinations_without_colour_var"/>
    <testcase time="0.00300000000004275" classname="g_expert_cl" name="coloring_ggplot_call_can_work_size_var"/>
    <testcase time="0.000999999999976353" classname="g_expert_cl" name="coloring_ggplot_call_can_work_size_var"/>
    <testcase time="0.00200000000006639" classname="g_expert_cl" name="coloring_ggplot_call_can_work_size_var"/>
  </testsuite>
  <testsuite name="scatterplotmatrix_get_stats" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="6" skipped="0" failures="0" errors="0" time="0.024">
    <testcase time="0.00899999999990087" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_numeric"/>
    <testcase time="0.00300000000004275" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_numeric"/>
    <testcase time="0.00300000000004275" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_numeric"/>
    <testcase time="0.0040000000000191" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_character"/>
    <testcase time="0.00199999999995271" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_character"/>
    <testcase time="0.00300000000004275" classname="scatterplotmatrix_get_stats" name="get_scatterplotmatrix_stats_x_y_character"/>
  </testsuite>
  <testsuite name="variable_browser" timestamp="2024-04-15T09:39:27Z" hostname="9f1a85ba1939" tests="3" skipped="0" failures="0" errors="0" time="0.013">
    <testcase time="0.00499999999999545" classname="variable_browser" name="remove_outliers_from_does_not_remove_outliers_when_outlier_definition_is_zero"/>
    <testcase time="0.00499999999999545" classname="variable_browser" name="remove_outliers_from_removes_outliers_when_outlier_definition_is_non_zero"/>
    <testcase time="0.00299999999992906" classname="variable_browser" name="remove_outliers_from_keeps_missing_values_unchanged"/>
  </testsuite>
</testsuites>
